# Generated by Django 2.0.6 on 2018-07-28 14:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Break',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_start', models.TimeField(verbose_name='Start time')),
                ('end_start', models.TimeField(verbose_name='End time')),
            ],
        ),
        migrations.CreateModel(
            name='DayOfWeek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='Day of week name')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Schedule owner')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_open', models.TimeField(verbose_name='Opening time')),
                ('close_open', models.TimeField(verbose_name='Closing time')),
                ('day_of_week_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.DayOfWeek', verbose_name='Day of week')),
                ('schedule_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Schedule', verbose_name='Schedule')),
            ],
        ),
        migrations.AddField(
            model_name='break',
            name='schedule_record_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.ScheduleRecord', verbose_name='Schedule record'),
        ),
    ]
