# Generated by Django 2.0.6 on 2018-07-28 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dayofweek',
            options={'verbose_name_plural': 'Days of week name'},
        ),
    ]
