# Generated by Django 2.0.6 on 2018-07-28 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20180728_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='name',
            field=models.CharField(default='Schedule1', max_length=200, verbose_name='Schedule name'),
            preserve_default=False,
        ),
    ]
