# Generated by Django 2.0.6 on 2018-07-28 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_schedule_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='break',
            old_name='end_start',
            new_name='time_end',
        ),
        migrations.RenameField(
            model_name='schedulerecord',
            old_name='close_open',
            new_name='time_close',
        ),
    ]
