# Generated by Django 2.0.6 on 2018-07-29 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20180728_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='break',
            name='name',
            field=models.CharField(default='Deaner break', max_length=200, verbose_name='Name'),
            preserve_default=False,
        ),
    ]
