# Generated by Django 2.0.6 on 2018-07-29 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_break_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='break',
            name='schedule_record_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breaks', to='shop.ScheduleRecord', verbose_name='Schedule record'),
        ),
    ]
