# Generated by Django 2.0.6 on 2018-07-29 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20180729_1605'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedulerecord',
            options={'ordering': ['day_of_week_id']},
        ),
    ]
