# Generated by Django 2.0.6 on 2018-07-30 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20180729_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulerecord',
            name='is_holiday',
            field=models.BooleanField(default=False, verbose_name='Is holiday'),
        ),
    ]
