# Generated by Django 2.0.6 on 2018-07-30 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_schedulerecord_is_holiday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulerecord',
            name='time_close',
            field=models.TimeField(null=True, verbose_name='Closing time'),
        ),
        migrations.AlterField(
            model_name='schedulerecord',
            name='time_open',
            field=models.TimeField(null=True, verbose_name='Opening time'),
        ),
    ]
