# Generated by Django 2.0.6 on 2018-07-30 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_auto_20180730_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='shop_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Shop', verbose_name='Schedule owner'),
        ),
    ]
