# Generated by Django 2.0.6 on 2018-07-30 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_auto_20180730_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='shop_id',
        ),
    ]
