# Generated by Django 2.0.6 on 2018-07-30 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_remove_schedule_shop_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='shop_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
