# Generated by Django 2.0.6 on 2018-07-30 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_schedule_shop_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='shop_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='shop.Shop', verbose_name='Schedule owner'),
        ),
    ]
