# Generated by Django 2.0.6 on 2018-07-30 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_shop_is_closed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='is_closed',
        ),
        migrations.AddField(
            model_name='shop',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
    ]
