# Generated by Django 2.0.6 on 2018-07-30 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_auto_20180730_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='shop_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='shop.Shop', verbose_name='Schedule owner'),
        ),
    ]
