# Generated by Django 2.0.6 on 2018-07-31 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_auto_20180730_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulerecord',
            name='schedule_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_recordsss', to='shop.Schedule', verbose_name='Schedule'),
        ),
    ]
