# Generated by Django 2.0.6 on 2018-07-25 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default=123456, max_length=200, verbose_name='Password'),
            preserve_default=False,
        ),
    ]
