# Generated by Django 2.0.6 on 2018-07-25 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_password'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='ShopUser',
        ),
    ]
