# Generated by Django 2.0.6 on 2018-07-27 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20180725_1818'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShopUser',
        ),
    ]
